export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { company, country, data } = req.body;
  if (!data) return res.status(400).json({ error: 'No package data provided' });

  const d = data;
  const ds = d.decision_support || {};
  const sc = ds.scores || {};
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0];
  const timeStr = now.toISOString().replace('T',' ').substring(0,16) + ' UTC';
  const safeCompany = (company||'partner').replace(/[^a-zA-Z0-9\s]/g,' ').trim();

  const frontmatter = (title) =>
`---
Partner: ${safeCompany}
Country: ${country||''}
Document: ${title}
Generated by: AI Operations Workspace
Model: claude-sonnet-4-6
Date: ${timeStr}
Status: Approved — Pending Review
---

`;

  // README
  const recLabel = ds.recommendation === 'approve' ? 'Approve Recommended'
    : ds.recommendation === 'review' ? 'Review Required' : 'Reject Recommended';

  const readme =
`# Partner Package — ${safeCompany}

| | |
|---|---|
| **Partner** | ${safeCompany} |
| **Country** | ${country||''} |
| **Generated** | ${timeStr} |
| **AI Assessment** | ${sc.overall||'--'} / 100 |
| **Recommendation** | ${recLabel} |
| **Status** | Approved — Pending Review |

## What's in this package

| File | Contents |
|---|---|
| \`01_AI_Assessment.md\` | Readiness scores, confidence rating, and flags |
| \`02_Qualification_Checklist.md\` | Due diligence checklist by category |
| \`03_Onboarding_Plan.md\` | Phased 8-week onboarding plan with owners |
| \`04_Internal_Brief.md\` | Team-level action items for Legal, Accounting, Logistics, Sales |
| \`05_Risk_Report.md\` | Risk register with impact, action, owner, and timeline |
| \`06_Welcome_Email.md\` | Draft welcome email ready for review and dispatch |

## Workflow

\`\`\`
Partner Submitted
      ↓
AI Assessment (claude-sonnet-4-6)
      ↓
Human Review (Approve / Review / Reject)
      ↓
Approved
      ↓
Partner Package Generated
\`\`\`

---
*This package was generated by AI Operations Workspace and reviewed and approved before execution. All documents should be reviewed before external distribution.*

*AI Operations Workspace — [ai-ops-workspace.vercel.app](https://ai-ops-workspace.vercel.app)*
`;

  // 01 AI Assessment
  const assessment = frontmatter('AI Assessment Report') +
`# AI Assessment Report

## Readiness Score

| Dimension | Score | |
|---|---|---|
| Qualification | ${sc.qualification||'--'} / 100 | Business verifiability |
| Compliance | ${sc.compliance||'--'} / 100 | Regulatory complexity |
| Operations | ${sc.operations||'--'} / 100 | Operational readiness |
| **Overall** | **${sc.overall||'--'} / 100** | Weighted average |

**AI Confidence:** ${ds.confidence||'--'}%
**Reason:** ${ds.confidence_note||''}

## Recommendation

> ${ds.recommendation_text||''}

## Flags

${(ds.reasons||[]).map(r => {
  const flag = typeof r === 'string' ? r : (r.flag||'');
  const impact = typeof r === 'object' ? (r.impact||'') : '';
  return `### ⚠ ${flag}\n${impact ? `**Impact:** ${impact}` : ''}`;
}).join('\n\n')}

---
*AI-assisted assessment. Human decision required before onboarding proceeds.*
`;

  // 02 Qualification Checklist
  let qual = frontmatter('Qualification Checklist') + '# Qualification Checklist\n\n';
  if (d.qualification && d.qualification.items) {
    d.qualification.items.forEach(section => {
      qual += `## ${section.section}\n\n`;
      (section.checks||[]).forEach(c => { qual += `- [ ] ${c}\n`; });
      qual += '\n';
    });
  }
  qual += '---\n*All items must be completed before proceeding to contract stage.*\n';

  // 03 Onboarding Plan
  let plan = frontmatter('Onboarding Plan') + '# Onboarding Plan\n\n';
  if (d.onboarding && d.onboarding.phases) {
    d.onboarding.phases.forEach(phase => {
      plan += `## ${phase.phase}\n`;
      if (phase.owner) plan += `**Owner:** ${phase.owner}\n\n`;
      (phase.tasks||[]).forEach(t => { plan += `- [ ] ${t}\n`; });
      plan += '\n';
    });
  }
  plan += '---\n*Timeline subject to completion of qualification checklist.*\n';

  // 04 Internal Brief
  const teamLabels = { legal:'Legal', accounting:'Accounting', logistics:'Logistics', sales:'Sales' };
  const statusIcon = { ok:'✓', warning:'⚠', required:'!' };
  let brief = frontmatter('Internal Brief') + '# Internal Brief\n\n';
  brief += `**For internal distribution only. Do not share with external parties.**\n\n`;
  if (d.internal_summary) {
    ['legal','accounting','logistics','sales'].forEach(t => {
      const team = d.internal_summary[t];
      if (!team) return;
      brief += `## ${teamLabels[t]}\n**Status:** ${team.status||'Pending'}\n\n`;
      (team.items||[]).forEach(item => {
        const icon = statusIcon[item.status] || '·';
        brief += `- ${icon} **${item.label}:** ${item.value}\n`;
      });
      brief += '\n';
    });
  }
  brief += '---\n*Distribute to respective team leads before onboarding kickoff.*\n';

  // 05 Risk Report
  let risk = frontmatter('Risk Report') + '# Risk Report\n\n';
  if (d.risks && d.risks.length) {
    ['high','medium','low'].forEach(level => {
      const levelRisks = d.risks.filter(r => r.level === level);
      if (!levelRisks.length) return;
      risk += `## ${level.charAt(0).toUpperCase()+level.slice(1)} Priority\n\n`;
      levelRisks.forEach(r => {
        risk += `### ${r.flag}\n\n`;
        risk += `| | |\n|---|---|\n`;
        risk += `| **Impact** | ${r.impact||''} |\n`;
        risk += `| **Recommended action** | ${r.mitigation||''} |\n`;
        risk += `| **Owner** | ${r.owner||''} |\n`;
        risk += `| **Timeline** | ${r.priority||''} |\n\n`;
      });
    });
  }
  risk += '---\n*All high-priority risks must be resolved before contract stage.*\n';

  // 06 Welcome Email
  let email = frontmatter('Welcome Email') + '# Welcome Email\n\n';
  if (d.email) {
    email += `**Subject:** ${d.email.subject}\n\n`;
    email += `---\n\n${d.email.body}\n`;
  }
  email += '\n---\n*Review and personalise before sending. Obtain sign-off from the relevant account owner.*\n';

  res.status(200).json({
    company: safeCompany,
    generated_at: now.toISOString(),
    files: {
      'README.md': readme,
      '01_AI_Assessment.md': assessment,
      '02_Qualification_Checklist.md': qual,
      '03_Onboarding_Plan.md': plan,
      '04_Internal_Brief.md': brief,
      '05_Risk_Report.md': risk,
      '06_Welcome_Email.md': email,
    }
  });
}
